apiVersion: v1
kind: Service
metadata:
  labels:
    app: espocrm
  name: espocrm
spec:
  type: NodePort
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  selector:
    app: espocrm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: espocrm
  name: espocrm-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: espocrm
  name: espocrm-upload
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: espocrm
  name: espocrm-custom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: espocrm-mysql
  name: espocrm-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: espocrm
  name: espocrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: espocrm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/espocrm-k8s-default: 'true'
        app: espocrm
    spec:
      containers:
        - env:
            - name: ESPOCRM_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_ADMIN_PASSWORD
                  name: espocrm-env
            - name: ESPOCRM_ADMIN_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_ADMIN_USERNAME
                  name: espocrm-env
            - name: ESPOCRM_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_DATABASE_HOST
                  name: espocrm-env
            - name: ESPOCRM_DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_DATABASE_PASSWORD
                  name: espocrm-env
            - name: ESPOCRM_DATABASE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_DATABASE_PLATFORM
                  name: espocrm-env
            - name: ESPOCRM_DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_DATABASE_USER
                  name: espocrm-env
            - name: ESPOCRM_SITE_URL
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_SITE_URL
                  name: espocrm-env
          image: espocrm/espocrm
          name: espocrm
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command:
                  - '/bin/bash'
                  - '-c'
                  - 'echo "* * * * * cd /var/www/html; /usr/local/bin/php -f cron.php > /dev/null 2>&1" > /etc/cron.d/espocrm;'
          volumeMounts:
            - mountPath: /var/www/html/data/logs
              name: espocrm-logs
            - mountPath: /var/www/html/data/upload
              name: espocrm-upload
            - mountPath: /var/www/html/custom/Espo
              name: espocrm-custom
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_DATABASE
                  name: espocrm-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_DATABASE_PASSWORD
                  name: espocrm-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_ADMIN_PASSWORD
                  name: espocrm-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: ESPOCRM_DATABASE_USER
                  name: espocrm-env
          image: mysql:8
          name: espocrm-mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: espocrm-mysql
      restartPolicy: Always
      volumes:
        - name: espocrm-logs
          persistentVolumeClaim:
            claimName: espocrm-logs
        - name: espocrm-upload
          persistentVolumeClaim:
            claimName: espocrm-upload
        - name: espocrm-custom
          persistentVolumeClaim:
            claimName: espocrm-custom
        - name: espocrm-mysql
          persistentVolumeClaim:
            claimName: espocrm-mysql
